version: "3.5"

services:
  db:
    image: mysql:8.0.21
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_USER: root
      MYSQL_PASSWORD: 123123
      MYSQL_DATABASE: breed
    ports:
      - "3307:3306"
    command: --sql_mode="" --log_bin_trust_function_creators=ON

volumes:
  db_data:
